hardware_acceleration:
  enable: True
  opencl: True
  backend: v4l2
smoothing:
  enable: True
  head: 0.7
  eyelids: 0.5
  pupils: 0.8
  mouth: 0.4
  brows: 0.5
  teeth: 0.4
  recording:
    fps: 30
    output_path: recordings
    auto_timestamp: True
calibration:
  file: calibration.json
  ref_points:
  - 33
  - 263
preview:
  fps: 30
  scale: 0.8
camera:
  width: auto
  height: auto
  preferred_format: MJPG  # 优先尝试的格式（MJPG/YUYV等）