name: Build and Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release Type (beta/release)'
        required: true
        default: 'beta'
      semver:
        description: 'Semantic Version (e.g. 1.0.0)'
        required: true

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
      tag: ${{ steps.set_version.outputs.tag }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set version info
      id: set_version
      shell: bash
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "version=${{ github.event.inputs.semver }}-${{ github.event.inputs.release_type }}" >> $GITHUB_OUTPUT
          echo "tag=v${{ github.event.inputs.semver }}-${{ github.event.inputs.release_type }}" >> $GITHUB_OUTPUT
        else
          COMMIT_SHA=$(git rev-parse --short HEAD)
          echo "version=canary-$COMMIT_SHA" >> $GITHUB_OUTPUT
          echo "tag=canary-$COMMIT_SHA" >> $GITHUB_OUTPUT
        fi

  build:
    needs: version
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install core dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller numpy pyyaml mediapipe

    - name: Build executable
      run: |
        pyinstaller -D -c --debug=all main.py

    - name: Package artifacts
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: Mozi_s_Facemocap_${{ needs.version.outputs.version }}_${{ runner.os }}.zip
        path: dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Mozi_s_Facemocap_${{ needs.version.outputs.version }}_${{ runner.os }}
        path: Mozi_s_Facemocap_${{ needs.version.outputs.version }}_${{ runner.os }}.zip

  release:
    needs: [version, build]
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ needs.version.outputs.tag }}
        name: Mozi's FacemoCap ${{ needs.version.outputs.version }}
        generate_release_notes: true
        files: |
          artifacts/**/*.zip
        replace: true