name: Build and Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release Type (beta/release)'
        required: true
        default: 'beta'
      semver:
        description: 'Semantic Version (e.g. 1.0.0)'
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install core dependencies
      run: |
        pip install pyinstaller numpy pyyaml
        # 显式安装 mediapipe 但不打包其资源
        pip install --no-deps mediapipe

    - name: Generate version info
      id: version
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "VERSION=${{ inputs.semver }}-${{ inputs.release_type }}" >> $GITHUB_ENV
        else
          echo "VERSION=canary-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        fi

    - name: Build executable
      run: |
        pyinstaller -D -c -w \
          --name FaceCap_${{ env.VERSION }} \
          --add-data "config.yaml:." \
          --add-data "README.md:." \
          --hidden-import mediapipe \
          --hidden-import yaml \
          main.py

    - name: Package artifacts
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: FaceCap_${{ env.VERSION }}_${{ runner.os }}.zip
        path: dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FaceCap_${{ env.VERSION }}_${{ runner.os }}
        path: FaceCap_${{ env.VERSION }}_${{ runner.os }}.zip

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        name: FaceCap ${{ env.VERSION }}
        files: |
          artifacts/**/*.zip